server:
  port: 8080

spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://db.qegvujunggqjtvvjrehm.supabase.co:5432/postgres

    username: postgres

    password: Shopkart@12345

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true












